### ISSUE TITLE
idnex.jsの場所について

### ISSUE THREAD

**Issue by CPkobo** [gecko655/proofreading-tool#22]
windows 10 にて。
cloneして yarn start したところ、”Failed to load resource: net::ERR_FILE_NOT_FOUND index.js” が出てうまく動きません。
ディレクトリ構造を見ると、index.js は assets/js/entries に入っていますが、index.html では assets/dist/index.js が指定されています。
インストーラー版は問題なく動いており、また assets/js/entries に書き換えると正常に動作しました。
リポジトリ側だけ残ってしまっているのでしょうか。

**Comment by gecko655** [comment]
事前に `yarn run webpack` していただくと動作すると思います。


開発の過程でいろいろあって、現在は「1つのjsファイルを1つのjsファイルにまとめる」webpackの実行が必要な状態になっています。
（min.js化しているので何もしていないわけではないですが……）

**Comment by CPkobo** [comment]
そうなのですね！わかりました、ありがとうございます。
